### ISSUE TITLE
Fields with a period cause failures in elastalert

### ISSUE THREAD

**Issue by ringersoll** [Nclose-ZA/elastalert_hive_alerter#3]
Having an issue identified using winlogbeat. When a field like event_id.TargetUserName in a match statement, elastalert fails with KeyError

**Comment by ringersoll** [comment]
Appears to be an issue with fields containing a period

**Comment by markus-nclose** [comment]
Hi @ringersoll .

Fields like that you would need to specify like this:
"{match[event_id][TargetUserName]}"
or
"{match[event_data][SubjectMachineName]}"

Let me know if you got it working.

**Comment by gregoj** [comment]
Hi Markus--

Thanks for the reply and the plugin!

@ringersoll actually refers to the eventuality where the filename itself has a literal `.` in it, and not that `event_data` is an object/dict.

As the plugin stands now it returns a KeyError because the dot notation is actually _working_ and breaking because it's not actually a dict.

Is there some escaping that can be done to allow for this eventuality? For whatever reason elastic beats drops these into elasticsearch this way so we're stuck with this format.

Thanks again!

**Comment by ringersoll** [comment]
changing the match appears to be working within the hive_alert_config however when using something like
hive_observable_data_mapping:
  - ip: "{match[event_data][IpAddress]}"

in the observable mapping, it's not creating the observable within hive.

Any suggestions that would resolve this?

**Comment by danielbrowne** [comment]
I suspect the pull request I have just created might fix the issue, @markus-nclose please let me know if this looks OK to you.

**Comment by danielbrowne** [comment]
I have merged, please let me know if this solves the problem.

**Comment by ringersoll** [comment]
It seems to be working!! Thanks guys.  This is going to be a big help for us

**Comment by webhead404** [comment]
I have a use case to add this same capability to the alert configuration itself. Is this possible? I have pulled down the code for this instead of Elastalert implementation.

**Comment by danielbrowne** [comment]
@webhead404 if I understand correctly I think you can already do this using the "hive_alert_config" key as described in the README?

**Comment by webhead404** [comment]
It throws an KeyError for me which I believe is related to this issue. I am using 

`title: {rule[rule.name]}`

**Comment by danielbrowne** [comment]
@webhead404 perhaps try {rule[alert][rule][name]}, I am not sure that dot-separated format will work.

**Comment by webhead404** [comment]
Index out of range. darn. Could this be done with `hive_alert_config_type:classic` ?

**Comment by danielbrowne** [comment]
@webhead404 you might have to open a new ticket with your error traceback and alert data included. I am not sure where that error is coming from, but I think this now seems like a different issue. You could try that classic switch and see if it makes a difference.

**Comment by webhead404** [comment]
Here you go @danielbrowne  #11

**Comment by danielbrowne** [comment]
@webhead404 I see in your config in the ticket you have '{[alert][rule][name]}'. I think that should be '{rule[alert][rule][name]}'? Does that help at all?

**Comment by webhead404** [comment]
Unfortunately not. Traceback says KeyError on alert.
